CREATE TABLE clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    phone VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE marketers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    ref_code VARCHAR(100) UNIQUE NOT NULL,
    visitors INTEGER DEFAULT 0,
    sales INTEGER DEFAULT 0,
    points INTEGER DEFAULT 0,
    balance DECIMAL(10,2) DEFAULT 0.00,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL,
    project_name VARCHAR(255) NOT NULL,
    business_type VARCHAR(100),
    project_description TEXT,
    platform TEXT,
    design TEXT,
    requirements TEXT,
    marketer_id BIGINT,
    payment_id BIGINT,

    status VARCHAR(30) DEFAULT 'new'
        CHECK (
            status IN (
                'new',
                'contacted',
                'waiting_payment',
                'paid',
                'in_progress',
                'completed',
                'cancelled'
            )
        ),

    price DECIMAL(10,2),
    created_at TIMESTAMPTZ DEFAULT NOW(),

    FOREIGN KEY (marketer_id)
        REFERENCES marketers(id),

    FOREIGN KEY (client_id)
        REFERENCES clients(id)
);

CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    marketer_id BIGINT,
    amount DECIMAL(10,2) NOT NULL,
    payment_method VARCHAR(50),

    status VARCHAR(20) DEFAULT 'pending'
        CHECK (
            status IN (
                'pending',
                'paid',
                'failed',
                'refunded'
            )
        ),

    transaction_id VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    paid_at TIMESTAMPTZ,

    FOREIGN KEY (client_id)
        REFERENCES clients(id),

    FOREIGN KEY (project_id)
        REFERENCES projects(id),

    FOREIGN KEY (marketer_id)
        REFERENCES marketers(id)
);